DROP TABLE IF EXISTS maps
CASCADE;
CREATE TABLE maps
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  date_created DATE NOT NULL
  -- map_latlong POINT NOT NULL
);
